name: codav
version: '0.1'
summary: Reads CODA SEPA payment XML files
description: |
    An "XML message for Credit Transfer Initiation" (ISO 20022 XML) file encodes European credit transfers (SEPA) in a standard way. It's often refered to as a "CODA (Coded Statement of Account) file". It requests the movement of funds from the debtor account to a creditor. CODAv is a desktop application that understands these electronic messages and serves as a viewer to verify the contents of these files. CODAv follows the Belgian implementation guidelines as defined by the Belgian sector federation Febelfin.
icon: data/codav.png
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  codav:
    command: desktop-launch $SNAP/bin/codav
    desktop: codav.desktop
    plugs:
      - desktop
      - home
      - x11

parts:
  codav:
    source: .
    plugin: cmake
    after:
      - desktop-gtk3
    override-build: |
      snapcraftctl build
      cp ../../../data/codav.desktop $SNAPCRAFT_PART_INSTALL/codav.desktop
      sed -i -e 's/Icon=codav/Icon=${SNAP}\/meta\/gui\/icon.png/' $SNAPCRAFT_PART_INSTALL/codav.desktop
    build-packages:
      - valac
      - libxml2-dev
    stage-packages:
      - libxml2
      - libcanberra-gtk3-module
